export const FETCH_PHONE_START = 'FETCH_PHONE_START'
export const FETCH_PHONE_SUCCESS = 'FETCH_PHONE_SUCCESS'
export const FETCH_PHONE_ERROR = 'FETCH_PHONE_ERROR'

export const LOAD_MORE_PHONE_START = 'LOAD_MORE_PHONE_START'
export const LOAD_MORE_PHONE_SUCCESS = 'LOAD_MORE_PHONE_SUCCESS'
export const LOAD_MORE_PHONE_ERROR = 'LOAD_MORE_PHONE_ERROR'

export const FETCH_PHONES_BY_ID_START = 'FETCH_PHONES_BY_ID_START'
export const FETCH_PHONES_BY_ID_SUCCESS = 'FETCH_PHONES_BY_ID_SUCCESS'
export const FETCH_PHONES_BY_ID_ERROR = 'FETCH_PHONES_BY_ID_ERROR'
